name: Run Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Get Repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build project
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # 4. Run test
      - name: Run Selenium Tests
        run: mvn test
